# Build time
FROM oven/bun:1-alpine as build

WORKDIR /app
ENV NODE_ENV production

COPY package.json .
COPY bun.lockb .
RUN bun install --production --silent --frozen-lockfile

COPY src src
COPY tsconfig.json .
RUN bun compile

# Run time
FROM gcr.io/distroless/base:nonroot

WORKDIR /app
ENV NODE_ENV production

COPY --from=build --chown=nonroot:nonroot /app/app.bun .

EXPOSE $PORT
ENTRYPOINT [ "./app.bun" ]