name: Repository Settings

on:
  push:
    branches:
      - main

jobs:
  branch_protection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure repository settings
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{
              "allow_auto_merge": true,
              "delete_branch_on_merge": true
            }'

      - name: Set up branch protection
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": true
              },
              "restrictions": null
            }'
